//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.14 at 03:33:41 AM MSK 
//

@javax.xml.bind.annotation.XmlSchema(xmlns = {
        @javax.xml.bind.annotation.XmlNs(prefix = "m", namespaceURI="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata"),
        @javax.xml.bind.annotation.XmlNs(prefix = "d", namespaceURI = "http://schemas.microsoft.com/ado/2007/08/dataservices")},
        namespace = "http://www.w3.org/2005/Atom", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.omega.app.model;
